### ISSUE TITLE
Results of proposed model

### ISSUE THREAD

**Issue by whduddhks** [addb-swstarlab/OANet#3]
Hi, It is interesting to find the relationship between Knob and workload using attention.

I wonder the performance evaluation results for the two networks(proposed, single).
Also,  I'm curious about the performance of benchmarks other than RocksDB.
I would appreciate it if you could show me the results of this.

Thank you.

**Comment by DELAB-Y** [comment]
We updated 'README.md' ( add link of OANet paper) and below figure is results of comparative experiments with OANet and other models.

RocksDB is DBMS(database management system) not benchmark. Did you mean other database? or other benchmark for RocksDB?

<img src="https://github.com/addb-swstarlab/OANet/blob/main/img/OANet-result.png?raw=true" width="70%" height="70%"/>

**Comment by whduddhks** [comment]
Thank you for your answer.

I mean for other benchmark for RocksDB.
But if you have any results from other DBMS, i wonder about it.
And any reason you chose RocksDB for your research?

**Comment by DELAB-Y** [comment]
The first reason we chose RocksDB is because we are using RocksDB in the project we are working on. 
And the second reason is that we need a sufficient amount of data to conduct the OANet experiments. 
RocksDB has accumulated enough data during the project, so we selected the DBMS to conduct the experiment as RocksDB.
Experimenting with other benchmarks or other DBMSs in RocksDB is also interesting to me, but it takes a lot of time to generate data for the experiment. 
Therefore, it seems difficult to proceed with the experiments right now. If we proceed with the experiment later, we will update the contents.

Thank you for a good comment.
