### ISSUE TITLE
About Scaler

### ISSUE THREAD

**Issue by kimkyeonghun** [addb-swstarlab/OANet#4]
In train.py, why use different Scaler for X and Y?

scaler_X = MinMaxScaler().fit(X_tr)
scaler_y = StandardScaler().fit(y_tr)

**Comment by DELAB-Y** [comment]
To use the data for regression analysis, the data needs to go through standardization.

Since the range of values of knob differs greatly for each knob put as input, scaler_X used minmaxscaler to eliminate the difference in the range of knob.

And the performance was actually better when scaler_X used minmaxscaler and scaler_y used standardscaler

**Comment by kimkyeonghun** [comment]
Thanks for your reply
