### ISSUE TITLE
Model architecture

### ISSUE THREAD

**Issue by whduddhks** [addb-swstarlab/OANet#5]
Hello, thanks for your work.

self.attention(self.embed_wk.permute((1,0,2)), self.res_x.permute((1,0,2)), self.res_x.permute((1,0,2)))
In this code, you use self.embed_wk, self.res_x, self.res_x for Query, Key and Value?

And How about use singleNet output "self.x_im" for Query, Key and Value?

Because there are some important knobs with given workloads, but there are important knobs irrelevant with given workloads.
if use self.embed_wk, self.res_x, self.res_x for Query, Key and Value, then I think it is not include second case.

If you tested it before, I want to know the results.

Thank you.

**Comment by DELAB-Y** [comment]
As you say, there may be important knobs regardless of the given workload. 
When we experimented, we didn't find knob that had the same importance for all workloads.
But since we haven't experimented with all the real-world data that can exist, let's assume that there are important knobs, regardless of the given workload .

If the knob is important regardless of the given workload, the importance of that knob will be high in the second case, and it will be as high in the first case.

And when checking the performance of a database, the workload that the database performs is determined as one, so the first case that gives importance to the important knob when given a specific workload is more appropriate than the second case.
